## Settings for the jsonParser. ##
## Edit entries below to have them reflect in the parser ##

SRC_JSON: Adventure_trip_INTJ_prompt4_1.json
SRC_DIR: ./Prompt4/

DEST_CSV: Adventure_trip_INTJ_prompt4_1.csv
DEST_DIR: ./CSV_files/Prompt4/

ANNOTATION_COLS: [compassion_score, coherence_score, correctness]
