## Settings for the jsonParser. ##
## Edit entries below to have them reflect in the parser ##

SRC_JSON: FeelingSad_ESFP_prompt1_1.json
SRC_DIR: ./Prompt1/

DEST_CSV: FeelingSad_ESFP_prompt1_1.csv
DEST_DIR: ./CSV_files/Prompt1/

ANNOTATION_COLS: [compassion_score, coherence_score, correctness]
